version: "3.9"

services:
  es:
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data:delegated
  kibana:
    depends_on:
      - es
    image: kibana:7.17.5
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
