version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data:delegated
    logging:
      driver: "none"
  kibana:
    depends_on:
      - es
    image: docker.elastic.co/kibana/kibana:7.17.5
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    volumes:
      - ./data/kibana:/usr/share/kibana/data:delegated
    ports:
      - 5601:5601
    logging:
      driver: "none"
